apiVersion: v1
kind: Service
metadata:
  name: opslab-api
  namespace: opslab
spec:
  selector:
    app: opslab-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
